services:
  postgres:
    image: postgres:alpine
    container_name: telecom_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telecom_db
    ports:
      - "5498:5432" # 5498 is your "door" from Windows to Docker
    volumes:
      - telecom_pgdata:/var/lib/postgresql/data
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  admin-panel:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=telecom_db
      - ADMINER_DESIGN=nette

volumes:
  telecom_pgdata:
