services:

  python:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/telecomDB
    volumes:
      - ../scripts:/app/scripts
      - ../src:/app/src
      - ../data:/app/data
    working_dir: /app

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=telecomDB
    ports:
      - "5498:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  admin-panel:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db


volumes:
  db_data:

